-- 코드를 작성해주세요
# select
#     YEAR(YM) AS YEAR
#     ROUND(AVG(PM_VAL1), 2) AS PM10,
#     ROUND(AVG(PM_VAL2), 2) AS PM2.5,
# from AIR_POLLUTION
# GROUP BY LOCATION1, LOCATION2, YEAR(YM)
# HAVING LOCATION2 = '수원'
# ORDER BY YEAR ASC;

select 
    YEAR(YM) AS YEAR,
    ROUND(AVG(PM_VAL1), 2) AS 'PM10',
    ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
from AIR_POLLUTION
GROUP BY LOCATION2, YEAR(YM)
HAVING LOCATION2 = '수원'
ORDER BY YEAR ASC;