-- 코드를 입력하세요
# SELECT HOUR, COUNT(*) AS COUNT
# FROM ANIMAL_OUTS
# WHERE 
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE TIME(DATETIME) BETWEEN '09:00' AND '19:59'
GROUP BY HOUR(DATETIME)
ORDER BY HOUR ASC
