-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF AS F
    Inner JOIN ICECREAM_INFO AS I
    ON F.FLAVOR = I.FLAVOR AND I.INGREDIENT_TYPE = 'fruit_based'
WHERE F.TOTAL_ORDER > 3000
ORDER BY F.TOTAL_ORDER DESC;