-- 코드를 작성해주세요
select SUM(SCORE) AS SCORE, HG.EMP_NO AS EMP_NO, HE.EMP_NAME AS EMP_NAME, HE.POSITION AS POSITION, HE.EMAIL AS EMAIL
FROM HR_GRADE HG
INNER JOIN HR_EMPLOYEES HE
    ON HG.EMP_NO = HE.EMP_NO
GROUP BY HG.EMP_NO, HG.YEAR
HAVING HG.YEAR = 2022
ORDER BY SCORE DESC LIMIT 1;