# SELECT OUTS.ANIMAL_ID, OUTS.NAME, INS.ANIMAL_ID, INS.NAME,
#         OUTS.DATETIME AS OUTS_DATETIME, INS.DATETIME AS INS_DATETIME
# FROM ANIMAL_OUTS OUTS
# JOIN ANIMAL_INS INS
#     ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
# WHERE OUTS.DATETIME > INS.DATETIME;

SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS
JOIN ANIMAL_INS INS
    ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE OUTS.DATETIME < INS.DATETIME
ORDER BY INS.DATETIME;